services:
  app:
    build: .
    container_name: jenkins-data
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - sonarqube
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30sec
      timeout: 10sec
      retries: 3
